name: probability-of-a-word
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - matplotlib
  - scipy
  - pylint
  - pip
  - pip:
    - seaborn
    - ipdb
    - mosestokenizer
    - gdown
    - nltk
    - sacremoses
    - rpy2
